import Head from 'next/head'
import react, {useEffect} from 'react'
import React from 'react'
import {useNavigate, Redirect} from 'react-router-dom'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "../node_modules/next/link"
import { Suspense, lazy } from 'react'
import Loginfigure from './loginfigure'

const Login= lazy((()=>import('./loginfigure')))
  

const Loginfig= lazy(()=>{
  return new Promise(resolve=>{
    setTimeout(()=>resolve(import("./loginfigure")),9000)
  });
});





export default function Home() {


  

  return (
    
    <div>
      
       <Suspense fallback={<div>Loading...</div>}>
        <div><Loginfig/></div>
      </Suspense>
       <Head>
        <title>Welcome to Project_Health</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Health.jpg" />
      </Head>
      
     
               
</div>
 
  )
}
